# The name of the workflow as it will appear in the "Actions" tab of the GitHub repository
name: Run API Tests and Generate Cypress Report

# Specifies the trigger for this workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 8 1-31 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cypress-e2e-api"
  cypress-e2e-api:
    # Name of a workflow
    name: Run on Chrome 107
    # Configures the job to run on the latest version of an Ubuntu Linux runner
    runs-on: ubuntu-latest
    # Configures the job to run on what Docker container
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@v3

      # Clean install the necessary dependencies
      - name: Install dependencies
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      # Run tests in the Chrome browser
      - name: Run Cypress tests
        env:
          CYPRESS_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm run test:chrome
        continue-on-error: true

      # Merge generated multiple JSON reports into a single index.json report file
      - name: Merge test results into one
        run: npm run report:merge

      # Generate an HTML report from a single index.json report file
      - name: Generate HTML report
        run: npm run report:generate

      # Publish generated static page i.e., index.html
      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
